# Generated by Django 3.2.9 on 2022-11-18 19:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20221117_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dp', models.ImageField(null=True, upload_to='')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
