# Generated by Django 3.2.9 on 2022-11-19 06:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20221118_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='myfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('about', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
