# Generated by Django 3.2.9 on 2022-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='myskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('value', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
