# Generated by Django 3.2.9 on 2022-11-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_myskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
