# Generated by Django 3.2.9 on 2022-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('projectname', models.CharField(max_length=200, null=True)),
                ('projecttype', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
